import Head from "next/head";
import Header from "../components/Header";
import { Container } from "reactstrap";
import CartTable from "../components/CartTable";
import CartTotal from "../components/CartTotal";

export default function Cart() {    
  return (
    <>
      <Head>
        <title>Mercadinho Bit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        <Container className="mb-5">
          <h1 className="my-5">
            Carrinho
          </h1>

          <CartTable/>
          <CartTotal/>

        </Container>
        
      </main>
    </>
  );
}
