import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "../components/Header";
import { Button, Container } from "reactstrap";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Mercadinho Bit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Header/>

      <main >
        <Container className="py-5 text-center">
          <h1 className="mt-5 display-1">O melhor Jeito de Compar o que você ama</h1>
          <p className="my-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Nobis officiis modi, animi culpa id sit earum fuga, vitae quam autem voluptates! Dolores, natus maxime. Sint quaerat illo omnis saepe nam.</p>
        
          <Link href="/Products">
            <Button color="dark" className="px-4 pb-2">
              Conheça Nossos Produtos!
            </Button>
          </Link>

        </Container>

      </main>
    </>
  );
}
