import Head from "next/head";
import Header from "../components/Header";
import { Container } from "reactstrap";
import ProductsList from "../components/ProductsList";
import { GetStaticProps, NextPage } from "next";
import { fetchProducts, ProductType } from "../services/products";
import { ReactNode } from "react";

export const getStaticProps: GetStaticProps = async () => {
  const products = await fetchProducts()

  return { props: { products }}
}



const Products: NextPage = (props: {
  children?: ReactNode
  products?: ProductType[]
}) => {
  return (
    <>
      <Head>
        <title>Mercadinho Bit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <Container className="mb-5">
          <h1 className="my-5">Nossos Produtos</h1>

          {<ProductsList products={props.products!}/>}
        </Container>
      </main>
    </>
  );
}

export default Products